@startuml
actor Librarian

participant ReaderController
participant ReaderService
Database Database

Librarian -> ReaderController : POST /search (SearchRequest)
activate ReaderController

ReaderController -> ReaderService : searchReaders(request.getPage(), request.getQuery())
activate ReaderService

ReaderService -> ReaderService : validateEmail(query.getEmail())

ReaderService -> Database : create search criteria (Email)
activate Database
Database --> ReaderService : return ReaderDetails
deactivate Database

ReaderService -> ReaderController : return List<ReaderDetails>
deactivate ReaderService

ReaderController -> Librarian : return ListResponse<ReaderView>
deactivate ReaderController

@enduml
