
services:
    postgres_in_lms_network:
        container_name: postgres_in_lms_network
        image: postgres:latest
        restart: unless-stopped
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        volumes:
            - "postgres_volume:/var/lib/postgresql/data"
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD", "pg_isready", "-U", "postgres" ]
            interval: 10s
            retries: 5
            timeout: 5s

    rabbitmq_in_lms_network:
        container_name: rabbitmq_in_lms_network
        image: rabbitmq:3-management
        restart: unless-stopped
        ports:
            - "5672:5672" # RabbitMQ main port
            - "15672:15672" # RabbitMQ management UI
        environment:
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest
        networks:
            - lms_network
        healthcheck:
            test: [ "CMD", "rabbitmqctl", "status" ]
            interval: 10s
            retries: 5
            timeout: 5s

networks:
    lms_network:
        name: lms_network

volumes:
    postgres_volume:
    uploaded_files_volume: