@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title GET book details by Isbn as librarian

actor "Librarian" as User
participant ":Rest" as Rest
participant "Ctrl:BookController" as Ctrl
participant "service:BookService" as Service
participant "repo:BookRepository" as Repo
participant ":BookViewMapper" as Mapper


activate User

User -> Rest: requests the top 5 books lent

Rest -> Ctrl: Top5();


Ctrl -> Mapper: toBookCountView(bookService.findTop5BooksLent()))
Mapper -> Service: findTop5BooksLent()
Service -> Repo: getTop5(BookCountDTO)
Repo --> Service: list<BookCountDTO>
Service --> Mapper: list<BookCountDTO>
Mapper --> Ctrl: ListResponse<>
Ctrl --> Rest: ListResponse<>
Rest --> User: ListResponse<>

@enduml
