@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

title WP#4B.15 Get Average Lending Duration

actor "Librarian" as Librarian
participant "System" as System
participant ":LendingController" as Ctrl
participant ":LendingService" as Service
participant ":LendingRepository" as LendingRepo
participant ":LendingViewMapper" as Mapper


note over Librarian : Librarian is\nauthenticated

Librarian -> System: get average lending duration

System -> Ctrl: getAvgDuration();

Ctrl -> Service: getAverageDuration()
Service -> LendingRepo: getAverageDuration()
LendingRepo --> Service: (average)
Service --> Ctrl: (averageString)
Ctrl -> Mapper: toLendingsAverageDurationView(overdueLendings)
Mapper --> Ctrl: (view)
Ctrl --> System: (view)
System --> Librarian: (average lending duration)

@enduml
