@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0
hide circle
hide methods

package Lending as PLending <<Frame>> {
    class Lending {
        - startDate
        - limitDate
        - returnDate
        - returned
    }
    class LendingNumber {
    }
    class Fine{
        - value
    }
}



class User {
    - username
    - password
}

class Librarian





package Book as PBook <<Frame>> {
    class Book
    class ISBN {
    - isbn: string
    }
}

package Reader as PReader <<Frame>> {
    class Reader{
        - birthDate
        - gdprConsent
        - booksOutstanding
    }
    class ReaderNumber
}


Lending "1" -down- "1" ISBN : uses
ReaderNumber "1" -up- "1" Lending : uses
Book "1" -up- "1" ISBN : identifies
Reader "1" -up- "1" ReaderNumber : identifies
Lending "1" -right- "0..1" Fine : may lead to
Librarian "1" -down- "*" Lending : registers
Librarian "1" -right- "1" User : is
Lending -left- LendingNumber : identifies

@enduml
