@startuml

hide circle
skinparam classAttributeIconSize 0

title PSOFT-G1 Rest Mapping

class "/api" as Resource <<interface>>{
    GET
    PUT
    PATCH
    POST
    DELETE
}

class "/readers" extends Resource{
'    GET : get all entities
    POST : create an entity in the collection (A11/B12)
}

class "?name={name}" as SearchReader extends "/readers"{
    GET : get filtered\n entities (A14)
}

class "/{year}/{seq}" as ReaderID extends "/readers"{
    GET : get specific reader (A13)
    PATCH : update specific\n\t reader details (A12)
}

class "/lendings" as ReaderLendings extends ReaderID{
}

class "?isbn={isbn}" extends ReaderLendings{
    GET : lendings of a reader,\n searched by ISBN (A16)
}

class "/authors" extends Resource{
'    GET : get all entities
    POST : create an entity in the collection (A3/B3)
}

class "/{authorNumber}" as AuthorID extends "/authors"{
    GET : get specific author (A5)
    PATCH : update specific\n author details (A4)
}

class "?name={name}" as SearchAuthor extends "/authors"{
    GET : get filtered\n entities (A6)
}

class "/books" extends Resource{
}

class "/{isbn}" extends "/books"{
    GET : get specific book (A9)
    PUT : create specific book (A7/B7)
    PATCH : update specific\n book details (A8)
}

class "?genre={genre}" extends "/books"{
    GET : get filtered\n entities (A10)
}

class "/lendings" extends Resource{
    POST : create an entity in the collection (A15)
}

class "/{year}/{seq}" as LendingID extends "/lendings"{
    GET : get specific lending (A17)
    PATCH : update lending\n (return book) (A16)
}

'
'PHASE 2
'

class "/books" as AuthorBooks extends AuthorID{
    GET : get books of\nan author (B4)
}

class "/coauthors" extends AuthorID{
    GET : get coauthors\nof an author (B5)
}

class "/top5" as TopAuthors extends "/authors"{
    GET : get top 5\nauthors (B6)
}

class "?title={title}" extends "/books"{
    GET : get books\nby title (B8)
}

class "/top5" as TopBooks extends "/books"{
    GET : get top 5\nbooks (B9)
}

class "/genres" extends Resource{
}

class "/top5" as TopGenres extends "/genres"{
    GET : get top 5\n genres with most\n books in library (B10)
}

class "/top5" as TopReaders extends "/readers"{
    GET : get top 5\nreaders (B11)
}

class "/suggestions" extends "/books"{
    GET : get list\nof suggestions (B13)
}

class "/overdue" extends "/lendings"{
    GET : list of overdue\n lendings (B23)
}

class "/avgLendings" extends "/genres"{
}

class "?period={day}&start={date}&end{date}" extends "/avgLendings"{
    GET: daily average number of \nlendings per genre (B14)
}

class "/avgDuration" extends "/lendings"{
    GET : average lending duration (B15)
}

class "?period={month}&count={12}" extends "/lendings"{
    GET : lendings/month last\n 12 mo, by genre (B16)
}

class "/top5readers" extends "/genres"{
    GET : get top 5\nreaders per genre (B17)
}
class "/monthlyLendings" as MonthlyLendings extends "/lendings"{
    GET : monthly lending per\nreader of a certain period (B18)
}
class "?period={month}&groupBy={genre}&begin={date}&end={date}" extends "/avgDuration"{
    GET : average lending duration (B19)
}

@enduml
